// Code generated by tachocard-tag-generator. DO NOT EDIT.

package tachocard

// Tag represents a tachograph card file identifier (FID).
type Tag uint16

// Defines the known tachograph card file identifiers.
const (
	// EF_ICC is the IC Card
	EF_ICC Tag = 0x0002
	// EF_IC is the Integrated Circuit Card
	EF_IC Tag = 0x0005
	// EF_Application_Identification is the Application Identification
	EF_Application_Identification Tag = 0x0501
	// EF_Card_Certificate is the Card Certificate
	EF_Card_Certificate Tag = 0x0502
	// EF_CA_Certificate is the CA Certificate
	EF_CA_Certificate Tag = 0x0503
	// EF_Identification is the Identification
	EF_Identification Tag = 0x0504
	// EF_Card_Download is the Card Download
	EF_Card_Download Tag = 0x0505
	// EF_Driving_License_Info is the Driving License Info
	EF_Driving_License_Info Tag = 0x0506
	// EF_Events_Data is the Events Data
	EF_Events_Data Tag = 0x0507
	// EF_Faults_Data is the Faults Data
	EF_Faults_Data Tag = 0x0508
	// EF_Driver_Activity_Data is the Driver Activity Data
	EF_Driver_Activity_Data Tag = 0x0509
	// EF_Vehicles_Used is the Vehicles Used
	EF_Vehicles_Used Tag = 0x050A
	// EF_Places is the Places
	EF_Places Tag = 0x050B
	// EF_Current_Usage is the Current Usage
	EF_Current_Usage Tag = 0x050C
	// EF_Control_Activity_Data is the Control Activity Data
	EF_Control_Activity_Data Tag = 0x050D
	// EF_Specific_Conditions is the Specific Conditions
	EF_Specific_Conditions Tag = 0x050E
)
