// Code generated by tachounit-tag-generator. DO NOT EDIT.

package tachounit

// DownloadType represents the type of data to be downloaded from a vehicle unit (TRTP).
type DownloadType byte

// Defines the known vehicle unit download types.
const (
	// TRTP_DownloadInterfaceVersion is for the Download interface version
	TRTP_DownloadInterfaceVersion DownloadType = 0x00
	// TRTP_Overview is for the Overview
	TRTP_Overview DownloadType = 0x01
	// TRTP_ActivitiesOfASpecifiedDate is for the Activities of a specified date
	TRTP_ActivitiesOfASpecifiedDate DownloadType = 0x02
	// TRTP_EventsAndFaults is for the Events and faults
	TRTP_EventsAndFaults DownloadType = 0x03
	// TRTP_DetailedSpeed is for the Detailed speed
	TRTP_DetailedSpeed DownloadType = 0x04
	// TRTP_TechnicalData is for the Technical data
	TRTP_TechnicalData DownloadType = 0x05
	// TRTP_Overview_0x15 is for the Overview
	TRTP_Overview_0x15 DownloadType = 0x15
	// TRTP_ActivitiesOfASpecifiedDate_0x16 is for the Activities of a specified date
	TRTP_ActivitiesOfASpecifiedDate_0x16 DownloadType = 0x16
	// TRTP_EventsAndFaults_0x17 is for the Events and faults
	TRTP_EventsAndFaults_0x17 DownloadType = 0x17
	// TRTP_DetailedSpeed_0x18 is for the Detailed speed
	TRTP_DetailedSpeed_0x18 DownloadType = 0x18
	// TRTP_TechnicalData_0x19 is for the Technical data
	TRTP_TechnicalData_0x19 DownloadType = 0x19
	// TRTP_Overview_0x1F is for the Overview
	TRTP_Overview_0x1F DownloadType = 0x1F
	// TRTP_ActivitiesOfASpecifiedDate_0x20 is for the Activities of a specified date
	TRTP_ActivitiesOfASpecifiedDate_0x20 DownloadType = 0x20
	// TRTP_EventsAndFaults_0x21 is for the Events and faults
	TRTP_EventsAndFaults_0x21 DownloadType = 0x21
	// TRTP_TechnicalData_0x23 is for the Technical data
	TRTP_TechnicalData_0x23 DownloadType = 0x23
)

// DataIdentifier represents a record data identifier for reading/writing VU data (RDI).
type DataIdentifier uint16

// Defines the known vehicle unit data identifiers.
const (
	// RDI_Vin is the VIN
	RDI_Vin DataIdentifier = 0xF190
	// RDI_Timedate is the TimeDate
	RDI_Timedate DataIdentifier = 0xF90B
	// RDI_Highresolutiontotalvehicledistance is the HighResolutionTotalVehicleDistance
	RDI_Highresolutiontotalvehicledistance DataIdentifier = 0xF912
	// RDI_Kfactor is the Kfactor
	RDI_Kfactor DataIdentifier = 0xF918
	// RDI_Lfactortyrecircumference is the LfactorTyreCircumference
	RDI_Lfactortyrecircumference DataIdentifier = 0xF91C
	// RDI_Wvehiclecharacteristicfactor is the WvehicleCharacteristicFactor
	RDI_Wvehiclecharacteristicfactor DataIdentifier = 0xF91D
	// RDI_Tyresize is the TyreSize
	RDI_Tyresize DataIdentifier = 0xF921
	// RDI_Nextcalibrationdate is the NextCalibrationDate
	RDI_Nextcalibrationdate DataIdentifier = 0xF922
	// RDI_Speedauthorised is the SpeedAuthorised
	RDI_Speedauthorised DataIdentifier = 0xF92C
	// RDI_Registeringmemberstate is the RegisteringMemberState
	RDI_Registeringmemberstate DataIdentifier = 0xF97D
	// RDI_Vehicleregistrationnumber is the VehicleRegistrationNumber
	RDI_Vehicleregistrationnumber DataIdentifier = 0xF97E
	// RDI_Motionsensorserialnumber is the MotionSensorSerialNumber
	RDI_Motionsensorserialnumber DataIdentifier = 0xF9D0
	// RDI_Remotecommunicationfacilityserialnumber is the RemoteCommunicationFacilitySerialNumber
	RDI_Remotecommunicationfacilityserialnumber DataIdentifier = 0xF9D1
	// RDI_Externalgnssfacilityserialnumber is the ExternalGNSSFacilitySerialNumber
	RDI_Externalgnssfacilityserialnumber DataIdentifier = 0xF9D2
	// RDI_Smarttachographsealsserialnumber is the SmartTachographSealsSerialNumber
	RDI_Smarttachographsealsserialnumber DataIdentifier = 0xF9D3
	// RDI_Vuserialnumber is the VuSerialNumber
	RDI_Vuserialnumber DataIdentifier = 0xF9D4
	// RDI_Bydefaultloadtype is the ByDefaultLoadType
	RDI_Bydefaultloadtype DataIdentifier = 0xF9D5
	// RDI_Tachographcardsgen1suppression is the TachographCardsGen1Suppression
	RDI_Tachographcardsgen1suppression DataIdentifier = 0xF9D6
	// RDI_Vehicleposition is the VehiclePosition
	RDI_Vehicleposition DataIdentifier = 0xF9D7
	// RDI_Calibrationcountry is the CalibrationCountry
	RDI_Calibrationcountry DataIdentifier = 0xF9D8
)
